-- DEVUSER 로 

-- Step 1
CALL SYSRDL#CG.REMOTE_EXECUTE ('
LOAD TABLE CATALOG_SALES
(
CS_SOLD_DATE_SK,
CS_SOLD_TIME_SK,
CS_SHIP_DATE_SK,
CS_BILL_CUSTOMER_SK,
CS_BILL_CDEMO_SK,
CS_BILL_HDEMO_SK,
CS_BILL_ADDR_SK,
CS_SHIP_CUSTOMER_SK,
CS_SHIP_CDEMO_SK,
CS_SHIP_HDEMO_SK,
CS_SHIP_ADDR_SK,
CS_CALL_CENTER_SK,
CS_CATALOG_PAGE_SK,
CS_SHIP_MODE_SK,
CS_WAREHOUSE_SK,
CS_ITEM_SK,
CS_PROMO_SK,
CS_ORDER_NUMBER,
CS_QUANTITY,
CS_WHOLESALE_COST,
CS_LIST_PRICE,
CS_SALES_PRICE,
CS_EXT_DISCOUNT_AMT,
CS_EXT_SALES_PRICE,
CS_EXT_WHOLESALE_COST,
CS_EXT_LIST_PRICE,
CS_EXT_TAX,
CS_COUPON_AMT,
CS_EXT_SHIP_COST,
CS_NET_PAID,
CS_NET_PAID_INC_TAX,
CS_NET_PAID_INC_SHIP,
CS_NET_PAID_INC_SHIP_TAX,
CS_NET_PROFIT
)
USING FILE ''S3://hanacloud/catalog_sales.dat''
DELIMITED BY ''|''
ROW DELIMITED BY ''\x0a''
ACCESS_KEY_ID ''AKIAIKRDGYHC2YTW64SA''
SECRET_ACCESS_KEY ''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''
REGION ''us-east-2''
ESCAPES OFF;
');

-- Step 2
CALL SYSRDL#CG.REMOTE_EXECUTE ('
LOAD TABLE STORE_SALES
(
  SS_SOLD_DATE_SK,
	SS_SOLD_TIME_SK,
	SS_ITEM_SK,
	SS_CUSTOMER_SK,
	SS_CDEMO_SK,
	SS_HDEMO_SK,
	SS_ADDR_SK,
	SS_STORE_SK,
	SS_PROMO_SK,
	SS_TICKET_NUMBER,
	SS_QUANTITY,
	SS_WHOLESALE_COST,
	SS_LIST_PRICE,
	SS_SALES_PRICE,
	SS_EXT_DISCOUNT_AMT,
	SS_EXT_SALES_PRICE,
	SS_EXT_WHOLESALE_COST,
	SS_EXT_LIST_PRICE,
	SS_EXT_TAX,
	SS_COUPON_AMT,
	SS_NET_PAID,
	SS_NET_PAID_INC_TAX,
	SS_NET_PROFIT
)
USING FILE ''S3://hanacloud/store_sales.dat''
DELIMITED BY ''|''
ROW DELIMITED BY ''\x0a''
ACCESS_KEY_ID ''AKIAIKRDGYHC2YTW64SA''
SECRET_ACCESS_KEY ''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''
REGION ''us-east-2''
ESCAPES OFF;
');
