-- Add a Replica to an Existing Virtual Table
ALTER VIRTUAL TABLE HANACLOUD_IRIS_DATA_TEST_TBL ADD SHARED REPLICA;

select * from M_VIRTUAL_TABLE_REPLICA;

select count(*) from HC_IRIS_DATA_TEST_TBL

select * from HC_IRIS_DATA_TEST_TBL WITH HINT(NO_VIRTUAL_TABLE_REPLICA)

ALTER VIRTUAL TABLE HC_IRIS_DATA_TEST_TBL DROP REPLICA;

select * from M_VIRTUAL_TABLE_REPLICA;

-- Replicating Tables from Remote Sources
CREATE COLUMN TABLE RT_IRIS_DATA_TRAIN_TBL LIKE HC_IRIS_DATA_TRAIN_TBL;

CREATE REMOTE SUBSCRIPTION SUB ON HC_IRIS_DATA_TRAIN_TBL TARGET TABLE RT_IRIS_DATA_TRAIN_TBL;

ALTER REMOTE SUBSCRIPTION SUB DISTRIBUTE;

select * from M_REMOTE_SUBSCRIPTIONS;

select count(*) from RT_IRIS_DATA_TRAIN_TBL;

ALTER REMOTE SUBSCRIPTION SUB RESET;

DROP REMOTE SUBSCRIPTION SUB;

